### ISSUE TITLE
Hardcoded SOLR fields

### ISSUE THREAD

**Issue by bradspry** [mjordan/islandora_bulk_delete#1]
islandora_bulk_delete.drush.inc

Hardcoded SOLR field names may not match system values, small adjustments to script may be needed for it to function.

For my system, I had "_mt" fields, not "_t" fields.   I had to make small adjustments to lines 86, 89, and 120 to make it work.

Maybe this could be documented or maybe it's just an expert level tool and a competent admin can figure it out :-)

**Comment by mjordan** [comment]
@bradspry yes, it does make assumptions about how your indexing is configured. Two approaches we could take are to allow users to pass in a drush option to identify which fields to query on, or to provide SPARQL queries that would bypass solr. The former sounds simpler.
